#!/usr/bin/env python3
"""Writes the ResidualData fixtures both readers are checked against.

The JSON header carries the keys of both writers (Rust: original_len;
Python: shape / dtype / quant_bits) so that either reader can parse the
same bytes. Only the "version" differs between the two files.
Run from the repository root: python3 tests/data/residual/make_fixtures.py
"""
import json
import struct
import zlib
from pathlib import Path

HERE = Path(__file__).resolve().parent
PAYLOAD = zlib.compress(struct.pack("<2f", 0.5, -1.25))

# version as the writers emit it (an integer) and in two spellings no writer
# emits: a float and a string; both readers must refuse the latter two
for version, name in ((2, "v2"), (3, "v3"), (2.0, "v2_float"), ("2", "v2_string")):
    header = json.dumps(
        {"method": "zlib", "original_len": 2, "shape": [2], "dtype": "float32",
         "quant_bits": None, "version": version},
        separators=(",", ":"),
    ).encode()
    (HERE / f"residual_{name}.bin").write_bytes(struct.pack("<I", len(header)) + header + PAYLOAD)

# delta: the values [5.0, 5.5, 6.0, 4.0] as float32 deltas, LZMA-compressed
#   delta_python_legacy: the earlier Python writer (first delta 0, the base is
#     lost) -> both readers refuse it
#   delta_rust_legacy: the earlier Rust writer (first delta = the first value,
#     "base_value" recorded, LZMA "alone" format as lzma-rs writes it) -> both
#     readers read it
#   bitdelta: the current writers (written below)
import lzma  # noqa: E402

VALUES = [5.0, 5.5, 6.0, 4.0]


def _deltas(first, fmt):
    out = [first] + [b - a for a, b in zip(VALUES, VALUES[1:])]
    return lzma.compress(struct.pack(f"<{len(out)}f", *out), format=fmt)


def _write(name, header, payload):
    h = json.dumps(header, separators=(",", ":")).encode()
    (HERE / f"residual_{name}.bin").write_bytes(struct.pack("<I", len(h)) + h + payload)


_common = {"original_len": 4, "shape": [4], "dtype": "float32", "quant_bits": None, "version": 2}
_write("delta_python_legacy", {"method": "delta", **_common}, _deltas(0.0, lzma.FORMAT_XZ))
_write("delta_rust_legacy", {"method": "delta", "base_value": 5.0, **_common}, _deltas(5.0, lzma.FORMAT_ALONE))
# bitdelta: the difference of consecutive f32 bit patterns as wrapping u32
# (the first difference is the first pattern), so every value comes back bit
# for bit; written in xz
def _bitdelta_stream(bits):
    out, prev = [], 0
    for b in bits:
        out.append((b - prev) & 0xFFFFFFFF)
        prev = b
    return struct.pack(f"<{len(out)}I", *out)


def _f32_bits(values):
    return list(struct.unpack(f"<{len(values)}I", struct.pack(f"<{len(values)}f", *values)))


_write("bitdelta", {"method": "bitdelta", **_common},
       lzma.compress(_bitdelta_stream(_f32_bits(VALUES)), format=lzma.FORMAT_XZ))

# the reference delta streams both encoders must produce, byte for byte:
# name | f32 bit patterns (hex) | delta stream (hex)
_vectors = {
    "magnitudes": _f32_bits([1e-8, 1.0, 1e8, 3.0]),
    "decimal": _f32_bits([0.1, 123456.7, 0.3]),
    "subnormal": [0x00000047, 0x3F800000, 0x00000047],  # ~1e-40, 1, ~1e-40
    "specials": [0x7FC00001, 0x3F800000, 0x7F800000, 0xFF800000, 0x80000000,
                 0x00000000, 0x00000001, 0x7F7FFFFF, 0xFFFFFFFF],
    "sterbenz": _f32_bits(VALUES),
}
with open(HERE / "bitdelta_streams.txt", "w") as f:
    f.write("# name | f32 bit patterns | delta stream (generated by make_fixtures.py)\n")
    for name, bits in _vectors.items():
        f.write(f"{name} | {' '.join(f'{b:08x}' for b in bits)} | {_bitdelta_stream(bits).hex()}\n")

# a header whose "shape" and "original_len" disagree: both readers refuse it
_write("shape_len_mismatch", {"method": "none", "original_len": 5, "shape": [4], "dtype": "float32",
                              "quant_bits": None, "version": 2}, struct.pack("<4f", *VALUES))


# dequantized values the readers must return for VALUES quantized by the
# writers (min 4.0, scale 2.0): code / (levels - 1) * scale + min in float64,
# then rounded to float32. Codes: 8 bits [128, 191, 255, 0], 16 bits
# [32768, 49151, 65535, 0] (round half to even, as numpy.round)
def _dequantized(codes, bits, scale=2.0, minimum=4.0):
    out = []
    for c in codes:
        v = c / (2 ** bits - 1) * scale + minimum
        out.append(struct.unpack("<I", struct.pack("<f", v))[0])
    return out


with open(HERE / "quantized_expected.txt", "w") as f:
    f.write("# name | float32 bit patterns (generated by make_fixtures.py)\n")
    f.write("quant8 | " + " ".join(f"{b:08x}" for b in _dequantized([128, 191, 255, 0], 8)) + "\n")
    f.write("quant16 | " + " ".join(f"{b:08x}" for b in _dequantized([32768, 49151, 65535, 0], 16)) + "\n")
    # Q32 = [0, 1, 0.5, 0.25] at 32 bits (min 0, scale 1): codes [0, 4294967295,
    # 2147483648, 1073741824], with 2147483647.5 and 1073741823.75 rounded half to even
    f.write("quant32 | " + " ".join(f"{b:08x}" for b in _dequantized(
        [0, 4294967295, 2147483648, 1073741824], 32, 1.0, 0.0)) + "\n")

# a dtype no writer records: both readers refuse it
_write("dtype_complex", {"method": "none", "shape": [4], "dtype": "complex64",
                         "quant_bits": None, "version": 2}, struct.pack("<4f", *VALUES))



# ---------------------------------------------------------------------------
# Random-valued residuals for the quantized fixtures of both writers
import sys  # noqa: E402

sys.path.insert(0, str(HERE))
from residual_values import random_values  # noqa: E402


# dequantized values the readers must return for random_values() quantized
# at 8 / 16 / 32 bits; float arithmetic as the writers do it, in float64:
# code = round_half_even((v - min) / scale * top), value = code / top * scale + min,
# then rounded once to float32 (struct)
def _random_dequantized(bits):
    vals = random_values()
    lo, hi = min(vals), max(vals)
    scale = hi - lo
    if scale < 1e-10:
        scale = 1.0
    top = float(2 ** bits - 1)
    out = []
    for v in vals:
        code = min(max(round((v - lo) / scale * top), 0), 2 ** bits - 1)
        out.append(struct.unpack("<I", struct.pack("<f", code / top * scale + lo))[0])
    return out


with open(HERE / "quantized_expected.txt", "a") as f:
    for _bits in (8, 16, 32):
        f.write(f"rand{_bits} | " + " ".join(f"{b:08x}" for b in _random_dequantized(_bits)) + "\n")


# ---------------------------------------------------------------------------
# reconstruct: original = generated (float64) + residual (float32), in
# float64, then the original's dtype. Integers: NaN is refused; otherwise
# rounded half to even and saturated to the dtype's range in the integer
# domain (inf saturates too). Floats: rounded once to the dtype (an overflow
# is an infinity). Computed with Python floats, ints and struct only.
INTS = {"int8": (8, True), "int16": (16, True), "int32": (32, True), "int64": (64, True),
        "uint8": (8, False), "uint16": (16, False), "uint32": (32, False), "uint64": (64, False)}
FLOATS = {"float16": "<e", "float32": "<f", "float64": "<d"}


def _f32(v):
    return struct.unpack("<f", struct.pack("<f", v))[0]


def _expected(dtype, s):
    if dtype in INTS:
        bits, signed = INTS[dtype]
        if s != s:
            return "error"
        lo, hi = (-(2 ** (bits - 1)), 2 ** (bits - 1) - 1) if signed else (0, 2 ** bits - 1)
        n = hi if s == float("inf") else lo if s == -float("inf") else round(s)
        n = min(max(n, lo), hi)
        return n.to_bytes(bits // 8, "little", signed=signed).hex()
    try:
        return struct.pack(FLOATS[dtype], s).hex()
    except OverflowError:
        return struct.pack(FLOATS[dtype], float("inf") if s > 0 else -float("inf")).hex()


def _vectors(dtype):
    inf, nan = float("inf"), float("nan")
    pairs = [(0.0, 0.0), (10.0, 0.5), (11.0, 0.5), (-10.0, -0.5), (-11.0, -0.5),
             (2.0, 0.25), (100.0, -36.54), (inf, 0.0), (-inf, 0.0), (nan, 0.0), (1.0, nan)]
    if dtype in INTS:
        bits, signed = INTS[dtype]
        lo, hi = (-(2 ** (bits - 1)), 2 ** (bits - 1) - 1) if signed else (0, 2 ** bits - 1)
        fhi, flo = float(hi), float(lo)
        below = math.nextafter(fhi, -inf) if fhi > hi else fhi
        for g in (fhi, below, fhi + 1.0, math.nextafter(fhi, inf), flo, flo - 1.0,
                  math.nextafter(flo, -inf), flo - 0.5, flo + 0.5, fhi - 0.5, fhi + 0.5,
                  float(hi // 2), -1.0, -0.5):
            pairs.append((g, 0.0))
        pairs.append((fhi - 1.0, 0.75))
    else:
        for g in (65504.0, 65519.99, 65520.0, 2.0 ** -25, 3 * 2.0 ** -25, 2.0 ** -24 * 0.75,
                  1e-8, 3.4028234663852886e38, 3.4028235677973366e38, 1e300, -1e300,
                  1.0 + 2.0 ** -11, 1.0 + 3 * 2.0 ** -11, 1.0 + 2.0 ** -24, 1.0 + 3 * 2.0 ** -24,
                  # around the smallest normal half 2^-14 (subnormal below it)
                  3 * 2.0 ** -16, 1.5 * 2.0 ** -15, 2.0 ** -14 - 2.0 ** -25, 2.0 ** -14 - 2.0 ** -23,
                  2.0 ** -14, 2.0 ** -14 + 2.0 ** -25):
            pairs.append((g, 0.0))
    bit_pairs = [(struct.unpack("<Q", struct.pack("<d", g))[0],
                  struct.unpack("<I", struct.pack("<f", _f32(r)))[0]) for g, r in pairs]
    # NaNs with payloads, signaling NaNs, negative NaNs, a NaN on each side and
    # on both, and inf + -inf (whose NaN the hardware gives differently)
    one, inf_b, ninf_b = 0x3FF0000000000000, 0x7FF0000000000000, 0xFFF0000000000000
    bit_pairs += [(0x7FF4000000000000, 0), (0x7FFFFFFFFFFFFFFF, 0), (0xFFF0040000000000, 0),
                  (0x7FF0000000000001, 0), (0x7FF0040000000000, 0), (0xFFF8000000000123, 0),
                  (one, 0x7F800001), (one, 0xFFC12345), (one, 0x7FFFFFFF), (one, 0xFF800001),
                  (0x7FF4000000000000, 0xFFC00001), (0x7FF8000000000001, 0x7F800001),
                  (inf_b, 0xFF800000), (ninf_b, 0x7F800000)]
    rows = []
    for gb, rb in bit_pairs:
        rows.append(f"{dtype} {gb:016x} {rb:08x} {_expected_bits(dtype, gb, rb)}")
    return rows


# The NaN of generated + residual, chosen by rule rather than by the
# hardware (which differs in which NaN it keeps and in the sign of the NaN of
# inf + -inf): generated's NaN with the quiet bit set; else the residual's NaN
# widened (sign, quiet bit, its 23 payload bits as the top of the 52); else
# (inf + -inf) the positive quiet NaN 0x7FF8000000000000
def _sum_nan_bits(gb, rb):
    g_nan = (gb >> 52) & 0x7FF == 0x7FF and gb & (2 ** 52 - 1)
    r_nan = (rb >> 23) & 0xFF == 0xFF and rb & (2 ** 23 - 1)
    if g_nan:
        return gb | 1 << 51
    if r_nan:
        return (rb >> 31) << 63 | 0x7FF8000000000000 | (rb & 0x7FFFFF) << 29
    return None


def _expected_bits(dtype, gb, rb):
    nan_bits = _sum_nan_bits(gb, rb)
    g = struct.unpack("<d", struct.pack("<Q", gb))[0]
    r = struct.unpack("<f", struct.pack("<I", rb))[0] if nan_bits is None else 0.0
    if nan_bits is None and abs(g) == float("inf") and abs(r) == float("inf") and g != r:
        nan_bits = 0x7FF8000000000000
    if nan_bits is None:
        return _expected(dtype, g + r)
    if dtype in INTS:
        return "error"
    # a NaN keeps its sign, the quiet bit and the top of its payload
    sign = nan_bits >> 63
    if dtype == "float16":
        return (sign << 15 | 0x7E00 | (nan_bits >> 42) & 0x3FF).to_bytes(2, "little").hex()
    if dtype == "float32":
        return (sign << 31 | 0x7FC00000 | (nan_bits >> 29) & 0x3FFFFF).to_bytes(4, "little").hex()
    return nan_bits.to_bytes(8, "little").hex()


import math  # noqa: E402

with open(HERE / "reconstruct_vectors.txt", "w") as f:
    f.write("# dtype | generated (float64 bits) | residual (float32 bits) | original as\n"
            "# little-endian bytes of the dtype, or error (generated by make_fixtures.py)\n")
    for _dt in ["float16", "float32", "float64", "int8", "int16", "int32", "int64",
                "uint8", "uint16", "uint32", "uint64"]:
        for _row in _vectors(_dt):
            f.write(_row + "\n")


# ---------------------------------------------------------------------------
# Lossless writing from the original (exceptions). Shared inputs of both
# writers: exception_cases.txt, rows `dtype original generated` with the
# original as little-endian hex of the dtype and generated as float64 bits.
# Specials (NaN payloads, signaling NaNs, infinities, -0, subnormals, the
# extremes), values from a linear congruential sequence, and generated values
# near the original, NaN, infinite or far away.
def _lcg(seed):
    x = seed
    while True:
        x = (x * 6364136223846793005 + 1442695040888963407) % 2 ** 64
        yield x


_FLOAT_SPECIALS = {
    2: [0x7E01, 0x7C01, 0x7C00, 0xFC00, 0x8000, 0x0001, 0x7BFF, 0xFE00],
    4: [0x7FC00001, 0x7F800001, 0x7F800000, 0xFF800000, 0x80000000, 0x00000001,
        0x7F7FFFFF, 0xFFC12345],
    8: [0x7FF8000000000001, 0x7FF0000000000001, 0x7FF0000000000000, 0xFFF0000000000000,
        0x8000000000000000, 0x0000000000000001, 0x7FEFFFFFFFFFFFFF, 0xFFF8000000012345],
}
_GEN_KINDS = ["near", "near", "nan", "inf", "-inf", "snan", "far", "near", "near", "exact"]


def _value_of(dtype, raw):
    if dtype in FLOATS:
        return struct.unpack(FLOATS[dtype], raw)[0]
    bits, signed = INTS[dtype]
    return float(int.from_bytes(raw, "little", signed=signed))


def _generated(kind, value):
    if kind == "nan":
        return 0x7FF8000000000123
    if kind == "snan":
        return 0x7FF0000000000001
    if kind in ("inf", "-inf"):
        return 0x7FF0000000000000 if kind == "inf" else 0xFFF0000000000000
    finite = value == value and abs(value) != float("inf")
    if kind == "far":
        g = 1e30
    elif kind == "exact":
        g = value if finite else 2.0
    else:
        g = value + 0.375 if finite else 2.0
    return struct.unpack("<Q", struct.pack("<d", g))[0]


def exception_cases():
    rows = []
    rng = _lcg(0x9E3779B97F4A7C15)
    for dtype in ["float16", "float32", "float64", "int8", "int16", "int32", "int64",
                  "uint8", "uint16", "uint32", "uint64"]:
        if dtype in FLOATS:
            width = struct.calcsize(FLOATS[dtype])
            originals = [b.to_bytes(width, "little") for b in _FLOAT_SPECIALS[width]]
            originals += [(next(rng) % 2 ** (8 * width)).to_bytes(width, "little") for _ in range(16)]
        else:
            bits, signed = INTS[dtype]
            width = bits // 8
            lo, hi = (-(2 ** (bits - 1)), 2 ** (bits - 1) - 1) if signed else (0, 2 ** bits - 1)
            ints = [lo, hi, 0, lo + 1, hi - 1, 1]
            ints += [lo + next(rng) % (hi - lo + 1) for _ in range(18)]
            originals = [n.to_bytes(width, "little", signed=signed) for n in ints]
        for i, raw in enumerate(originals):
            g = _generated(_GEN_KINDS[i % len(_GEN_KINDS)], _value_of(dtype, raw))
            rows.append(f"{dtype} {raw.hex()} {g:016x}")
    return rows


with open(HERE / "exception_cases.txt", "w") as f:
    f.write("# dtype | original (little-endian bytes of the dtype) | generated (float64 bits)\n"
            "# shared input of both lossless writers (generated by make_fixtures.py)\n")
    for _row in exception_cases():
        f.write(_row + "\n")


# files with exceptions that both readers refuse (method none, 4 values,
# exception block = positions (u64) then the original elements)
def _exc(name, header_extra, positions, elements=None, version=3, residual=None):
    header = {"method": "none", "shape": [4], "dtype": "float32", "quant_bits": None,
              "version": version, **header_extra}
    residual = residual if residual is not None else [5.0, 0.0, 6.0, 4.0]
    elements = elements if elements is not None else [b"\x00\x00\xc0\x7f"] * len(positions)
    block = b"".join(struct.pack("<Q", p) for p in positions) + b"".join(elements)
    _write(name, header, struct.pack("<4f", *residual) + block)


_exc("exc_v3_without_key", {}, [1])
_exc("exc_v2_with_key", {"exceptions": 1}, [1], version=2)
_exc("exc_unsorted", {"exceptions": 2}, [2, 1])
_exc("exc_duplicate", {"exceptions": 2}, [1, 1])
_exc("exc_out_of_range", {"exceptions": 1}, [4])
_exc("exc_zero", {"exceptions": 0}, [])
_exc("exc_count_disagrees", {"exceptions": 2}, [1])
_exc("exc_quantized", {"exceptions": 1, "method": "quantized", "quant_bits": 8}, [1])
# a well-formed one: positions 1 and 3 hold NaN and -inf bits
_exc("exc_ok", {"exceptions": 2}, [1, 3], [b"\x01\x00\xc0\x7f", b"\x00\x00\x80\xff"],
     residual=[5.0, 0.0, 6.0, 0.0])
