#!/usr/bin/env python3
"""Writes the ResidualData fixtures both readers are checked against.

The JSON header carries the keys of both writers (Rust: original_len;
Python: shape / dtype / quant_bits) so that either reader can parse the
same bytes. Only the "version" differs between the two files.
Run from the repository root: python3 tests/data/residual/make_fixtures.py
"""
import json
import struct
import zlib
from pathlib import Path

HERE = Path(__file__).resolve().parent
PAYLOAD = zlib.compress(struct.pack("<2f", 0.5, -1.25))

# version as the writers emit it (an integer) and in two spellings no writer
# emits: a float and a string; both readers must refuse the latter two
for version, name in ((2, "v2"), (3, "v3"), (2.0, "v2_float"), ("2", "v2_string")):
    header = json.dumps(
        {"method": "zlib", "original_len": 2, "shape": [2], "dtype": "float32",
         "quant_bits": None, "version": version},
        separators=(",", ":"),
    ).encode()
    (HERE / f"residual_{name}.bin").write_bytes(struct.pack("<I", len(header)) + header + PAYLOAD)

# delta: the values [5.0, 5.5, 6.0, 4.0] as float32 deltas, LZMA-compressed
#   delta_python_legacy: the earlier Python writer (first delta 0, the base is
#     lost) -> both readers refuse it
#   delta_rust_legacy: the earlier Rust writer (first delta = the first value,
#     "base_value" recorded, LZMA "alone" format as lzma-rs writes it) -> both
#     readers read it
#   bitdelta: the current writers (written below)
import lzma  # noqa: E402

VALUES = [5.0, 5.5, 6.0, 4.0]


def _deltas(first, fmt):
    out = [first] + [b - a for a, b in zip(VALUES, VALUES[1:])]
    return lzma.compress(struct.pack(f"<{len(out)}f", *out), format=fmt)


def _write(name, header, payload):
    h = json.dumps(header, separators=(",", ":")).encode()
    (HERE / f"residual_{name}.bin").write_bytes(struct.pack("<I", len(h)) + h + payload)


_common = {"original_len": 4, "shape": [4], "dtype": "float32", "quant_bits": None, "version": 2}
_write("delta_python_legacy", {"method": "delta", **_common}, _deltas(0.0, lzma.FORMAT_XZ))
_write("delta_rust_legacy", {"method": "delta", "base_value": 5.0, **_common}, _deltas(5.0, lzma.FORMAT_ALONE))
# bitdelta: the difference of consecutive f32 bit patterns as wrapping u32
# (the first difference is the first pattern), so every value comes back bit
# for bit; written in xz
def _bitdelta_stream(bits):
    out, prev = [], 0
    for b in bits:
        out.append((b - prev) & 0xFFFFFFFF)
        prev = b
    return struct.pack(f"<{len(out)}I", *out)


def _f32_bits(values):
    return list(struct.unpack(f"<{len(values)}I", struct.pack(f"<{len(values)}f", *values)))


_write("bitdelta", {"method": "bitdelta", **_common},
       lzma.compress(_bitdelta_stream(_f32_bits(VALUES)), format=lzma.FORMAT_XZ))

# the reference delta streams both encoders must produce, byte for byte:
# name | f32 bit patterns (hex) | delta stream (hex)
_vectors = {
    "magnitudes": _f32_bits([1e-8, 1.0, 1e8, 3.0]),
    "decimal": _f32_bits([0.1, 123456.7, 0.3]),
    "subnormal": [0x00000047, 0x3F800000, 0x00000047],  # ~1e-40, 1, ~1e-40
    "specials": [0x7FC00001, 0x3F800000, 0x7F800000, 0xFF800000, 0x80000000,
                 0x00000000, 0x00000001, 0x7F7FFFFF, 0xFFFFFFFF],
    "sterbenz": _f32_bits(VALUES),
}
with open(HERE / "bitdelta_streams.txt", "w") as f:
    f.write("# name | f32 bit patterns | delta stream (generated by make_fixtures.py)\n")
    for name, bits in _vectors.items():
        f.write(f"{name} | {' '.join(f'{b:08x}' for b in bits)} | {_bitdelta_stream(bits).hex()}\n")

# a header whose "shape" and "original_len" disagree: both readers refuse it
_write("shape_len_mismatch", {"method": "none", "original_len": 5, "shape": [4], "dtype": "float32",
                              "quant_bits": None, "version": 2}, struct.pack("<4f", *VALUES))


# dequantized values the readers must return for VALUES quantized by the
# writers (min 4.0, scale 2.0): code / (levels - 1) * scale + min in float64,
# then rounded to float32. Codes: 8 bits [128, 191, 255, 0], 16 bits
# [32768, 49151, 65535, 0] (round half to even, as numpy.round)
def _dequantized(codes, bits):
    out = []
    for c in codes:
        v = c / (2 ** bits - 1) * 2.0 + 4.0
        out.append(struct.unpack("<I", struct.pack("<f", v))[0])
    return out


with open(HERE / "quantized_expected.txt", "w") as f:
    f.write("# name | float32 bit patterns (generated by make_fixtures.py)\n")
    f.write("quant8 | " + " ".join(f"{b:08x}" for b in _dequantized([128, 191, 255, 0], 8)) + "\n")
    f.write("quant16 | " + " ".join(f"{b:08x}" for b in _dequantized([32768, 49151, 65535, 0], 16)) + "\n")

# a dtype no writer records: both readers refuse it
_write("dtype_complex", {"method": "none", "shape": [4], "dtype": "complex64",
                         "quant_bits": None, "version": 2}, struct.pack("<4f", *VALUES))

