"""Header values each residual version takes (tests/data/residual/
header_gating.txt, generated by make_fixtures.py as a matrix of key x JSON
value kind x version, each verdict from a spec written there, not from a
reader; shared with libalice/tests/residual_header_gating.rs). Both readers
must give every verdict."""
import struct
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from alice_zip.residual_compression import ResidualData  # noqa: E402

DATA = ROOT / "tests" / "data" / "residual"
_LINES = [l for l in (DATA / "header_gating.txt").read_text().splitlines()
          if l and not l.startswith("#")]
BASES = {int(l.split()[1]): bytes.fromhex(l.split()[2]) for l in _LINES if l.startswith("base ")}
ROWS = [l.split(" ", 3) for l in _LINES if not l.startswith("base ")]


def file_of(version, header):
    h = header.encode()
    return struct.pack("<I", len(h)) + h + BASES[int(version)]


def test_the_table_has_every_cell():
    assert sorted(BASES) == [2, 3, 4]
    assert len(ROWS) == 381
    assert {r[1] for r in ROWS} == {"accept", "refuse"}


@pytest.mark.parametrize("version,verdict,cell,header", ROWS, ids=lambda v: str(v)[:40])
def test_the_python_reader_gives_the_verdict(version, verdict, cell, header):
    data = file_of(version, header)
    if verdict == "refuse":
        with pytest.raises(ValueError):
            ResidualData.from_bytes(data)
    else:
        ResidualData.from_bytes(data)
