//! Header values each residual version takes (tests/data/residual/
//! header_gating.txt, generated by make_fixtures.py as a matrix of key x JSON
//! value kind x version, each verdict from a spec written there, not from a
//! reader; shared with tests/test_residual_header_gating.py). Both readers
//! must give every verdict.

use std::collections::HashMap;
use std::path::Path;

use alice_core::residual::ResidualData;

fn hex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

#[test]
fn the_rust_reader_gives_every_verdict() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../tests/data/residual");
    let table = std::fs::read_to_string(dir.join("header_gating.txt")).unwrap();
    let lines: Vec<&str> = table
        .lines()
        .filter(|l| !l.starts_with('#') && !l.is_empty())
        .collect();
    let bases: HashMap<&str, Vec<u8>> = lines
        .iter()
        .filter_map(|l| l.strip_prefix("base "))
        .map(|l| {
            let (v, p) = l.split_once(' ').unwrap();
            (v, hex(p))
        })
        .collect();
    assert_eq!(bases.len(), 3);
    let mut wrong = Vec::new();
    let mut compared = 0;
    for line in lines.iter().filter(|l| !l.starts_with("base ")) {
        let c: Vec<&str> = line.splitn(4, ' ').collect();
        let header = c[3].as_bytes();
        let mut data = u32::try_from(header.len()).unwrap().to_le_bytes().to_vec();
        data.extend_from_slice(header);
        data.extend_from_slice(&bases[c[0]]);
        let read = ResidualData::from_bytes(&data);
        if read.is_ok() != (c[1] == "accept") {
            wrong.push(format!("{line}: {:?}", read.err()));
        }
        compared += 1;
    }
    assert!(
        wrong.is_empty(),
        "{} cells differ:\n{}",
        wrong.len(),
        wrong.join("\n")
    );
    assert_eq!(compared, 375);
}
